@host=localhost:5000
@userID=66243ff433824491c4c968eb

###
# @name postHabits
# @prompt name Habit name
POST /habits HTTP/1.1
Host: {{host}}
Authorization: {{userID}}

{
    "name": "{{name}}",
    "scheduled": [false, true, false, true, false, true, false]
}

###
# @name getHabits
GET /habits HTTP/1.1
Host: {{host}}
Authorization: {{userID}}

###
# @name putHabit
# @prompt habitID Habit ID
# @prompt name New habit name
PUT /habits/{{habitID}} HTTP/1.1
Host: {{host}}
Authorization: {{userID}}

{
    "name": "{{name}}",
    "scheduled": [false, true, false, true, false, true, false],
    "completed": [false, true, false, false, false, false, false]
}