@host=localhost:5000
@token=vZxpJOWbRgfkFs9f3y-E_F04rMivVZn91UsDT-3WHGQ

###
# @name postTasks
# @prompt name Task name
POST /tasks HTTP/1.1
Host: {{host}}
Authorization: {{token}}

{
    "name": "{{name}}"
}

###
# @name getTasks
GET /tasks HTTP/1.1
Host: {{host}}
Authorization: {{token}}

###
# @name putTask
# @prompt taskID Task ID
# @prompt name New task name
PUT /tasks/{{taskID}} HTTP/1.1
Host: {{host}}
Authorization: {{token}}

{
    "name": "{{name}}",
    "priority": true,
    "completed": true
}

###
# @name deleteTask
# @prompt taskID Task ID
DELETE /tasks/{{taskID}} HTTP/1.1
Host: {{host}}
Authorization: {{token}}
